
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/hyperledger/fabric"
  version = "1.1.0-preview"

[[constraint]]
  name = "github.com/op/go-logging"
  revision = "970db520ece77730c7e4724c61121037378659d9"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.1"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/hyperledger/fabric-sdk-go"

[[constraint]]
  name = "github.com/cloudflare/cfssl"
  branch = "master"

[[constraint]]
  name = "golang.org/x/sync"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"
