// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package chaincode_example02 is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	Test
*/
package chaincode_example02

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Test struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Balance int32  `protobuf:"varint,2,opt,name=balance" json:"balance,omitempty"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Test) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Test) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*Test)(nil), "chaincode_example02.test")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4e, 0xce, 0x48, 0xcc, 0xcc, 0x4b, 0xce, 0x4f,
	0x49, 0x8d, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x35, 0x30, 0x52, 0x32, 0xe0, 0x62, 0x01,
	0x29, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca,
	0x4c, 0x11, 0x92, 0xe0, 0x62, 0x4f, 0x4a, 0xcc, 0x49, 0xcc, 0x4b, 0x4e, 0x95, 0x60, 0x52, 0x60,
	0xd4, 0x60, 0x0d, 0x82, 0x71, 0x93, 0xd8, 0xc0, 0xa6, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x98, 0x9a, 0xac, 0x33, 0x5b, 0x00, 0x00, 0x00,
}
