// Code generated by protoc-gen-go. DO NOT EDIT.
// source: member/member.proto

/*
Package member is a generated protocol buffer package.

It is generated from these files:
	member/member.proto

It has these top-level messages:
	Member
	MemberCreateRequest
	MemberQueryRequest
	MemberInfoResponse
*/
package member

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "diviner/protos/common"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Member struct {
	Id      string             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Address string             `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Balance float64            `protobuf:"fixed64,3,opt,name=balance" json:"balance,omitempty"`
	Assets  map[string]float64 `protobuf:"bytes,4,rep,name=assets" json:"assets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Member) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Member) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Member) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Member) GetAssets() map[string]float64 {
	if m != nil {
		return m.Assets
	}
	return nil
}

type MemberCreateRequest struct {
	Member *Member              `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
	Check  *common.Verification `protobuf:"bytes,2,opt,name=check" json:"check,omitempty"`
}

func (m *MemberCreateRequest) Reset()                    { *m = MemberCreateRequest{} }
func (m *MemberCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*MemberCreateRequest) ProtoMessage()               {}
func (*MemberCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MemberCreateRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *MemberCreateRequest) GetCheck() *common.Verification {
	if m != nil {
		return m.Check
	}
	return nil
}

type MemberQueryRequest struct {
	Id    string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Check *common.Verification `protobuf:"bytes,2,opt,name=check" json:"check,omitempty"`
}

func (m *MemberQueryRequest) Reset()                    { *m = MemberQueryRequest{} }
func (m *MemberQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*MemberQueryRequest) ProtoMessage()               {}
func (*MemberQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MemberQueryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MemberQueryRequest) GetCheck() *common.Verification {
	if m != nil {
		return m.Check
	}
	return nil
}

type MemberInfoResponse struct {
	Member *Member                    `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
	Time   *google_protobuf.Timestamp `protobuf:"bytes,999,opt,name=time" json:"time,omitempty"`
}

func (m *MemberInfoResponse) Reset()                    { *m = MemberInfoResponse{} }
func (m *MemberInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*MemberInfoResponse) ProtoMessage()               {}
func (*MemberInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MemberInfoResponse) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *MemberInfoResponse) GetTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*Member)(nil), "member.Member")
	proto.RegisterType((*MemberCreateRequest)(nil), "member.MemberCreateRequest")
	proto.RegisterType((*MemberQueryRequest)(nil), "member.MemberQueryRequest")
	proto.RegisterType((*MemberInfoResponse)(nil), "member.MemberInfoResponse")
}

func init() { proto.RegisterFile("member/member.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x41, 0x4b, 0xf3, 0x40,
	0x14, 0x64, 0xd3, 0x36, 0xe5, 0x7b, 0x81, 0xf2, 0xb1, 0xed, 0x21, 0xe4, 0x62, 0xe9, 0x41, 0x8a,
	0x87, 0x0d, 0xc4, 0x8b, 0x7a, 0x13, 0xf1, 0xe0, 0x41, 0xd0, 0x45, 0xbc, 0x6f, 0x92, 0xd7, 0xba,
	0xb4, 0x9b, 0xad, 0xbb, 0x1b, 0xa1, 0xbf, 0xcd, 0x1f, 0xe4, 0xdf, 0x90, 0xec, 0x26, 0xa0, 0x9e,
	0xf4, 0xb4, 0x99, 0x37, 0x93, 0x79, 0xc3, 0x1b, 0x98, 0x2b, 0x54, 0x25, 0x9a, 0x3c, 0x3c, 0xec,
	0x60, 0xb4, 0xd3, 0x34, 0x0e, 0x28, 0x9b, 0x57, 0x5a, 0x29, 0xdd, 0xe4, 0xe1, 0x09, 0x64, 0x76,
	0xb2, 0xd5, 0x7a, 0xbb, 0xc7, 0xdc, 0xa3, 0xb2, 0xdd, 0xe4, 0x4e, 0x2a, 0xb4, 0x4e, 0xa8, 0x43,
	0x10, 0xac, 0xde, 0x09, 0xc4, 0xf7, 0xde, 0x80, 0xce, 0x20, 0x92, 0x75, 0x4a, 0x96, 0x64, 0xfd,
	0x8f, 0x47, 0xb2, 0xa6, 0x29, 0x4c, 0x45, 0x5d, 0x1b, 0xb4, 0x36, 0x8d, 0xfc, 0x70, 0x80, 0x1d,
	0x53, 0x8a, 0xbd, 0x68, 0x2a, 0x4c, 0x47, 0x4b, 0xb2, 0x26, 0x7c, 0x80, 0xb4, 0x80, 0x58, 0x58,
	0x8b, 0xce, 0xa6, 0xe3, 0xe5, 0x68, 0x9d, 0x14, 0x19, 0xeb, 0xb3, 0x86, 0x1d, 0xec, 0xda, 0x93,
	0xb7, 0x8d, 0x33, 0x47, 0xde, 0x2b, 0xb3, 0x4b, 0x48, 0xbe, 0x8c, 0xe9, 0x7f, 0x18, 0xed, 0xf0,
	0xd8, 0xe7, 0xe8, 0x3e, 0xe9, 0x02, 0x26, 0x6f, 0x62, 0xdf, 0xa2, 0x8f, 0x41, 0x78, 0x00, 0x57,
	0xd1, 0x05, 0x59, 0x49, 0x98, 0x07, 0xe3, 0x1b, 0x83, 0xc2, 0x21, 0xc7, 0xd7, 0x16, 0xad, 0xa3,
	0xa7, 0xd0, 0x1f, 0xc5, 0xbb, 0x24, 0xc5, 0xec, 0x7b, 0x0a, 0xde, 0xb3, 0xf4, 0x0c, 0x26, 0xd5,
	0x0b, 0x56, 0x3b, 0x6f, 0x9c, 0x14, 0x0b, 0xd6, 0xdf, 0xee, 0x19, 0x8d, 0xdc, 0xc8, 0x4a, 0x38,
	0xa9, 0x1b, 0x1e, 0x24, 0xab, 0x07, 0xa0, 0xe1, 0xef, 0xc7, 0x16, 0xcd, 0x71, 0xd8, 0xf4, 0xf3,
	0x66, 0x7f, 0x71, 0x54, 0x83, 0xe3, 0x5d, 0xb3, 0xd1, 0x1c, 0xed, 0x41, 0x37, 0x16, 0x7f, 0x9d,
	0x3d, 0x87, 0x71, 0xd7, 0x65, 0xfa, 0x31, 0xf5, 0xb2, 0x8c, 0x85, 0xa6, 0xd9, 0xd0, 0x34, 0x7b,
	0x1a, 0x9a, 0xe6, 0x5e, 0x58, 0xc6, 0x9e, 0x39, 0xff, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x91,
	0x64, 0x79, 0x45, 0x02, 0x00, 0x00,
}
