// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lmsr/asset.proto

/*
Package lmsr is a generated protocol buffer package.

It is generated from these files:
	lmsr/asset.proto
	lmsr/event.proto
	lmsr/market.proto

It has these top-level messages:
	Asset
	Outcome
	Event
	Market
	Markets
*/
package lmsr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Asset struct {
	Id     string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Volume float64 `protobuf:"fixed64,2,opt,name=volume" json:"volume,omitempty"`
}

func (m *Asset) Reset()                    { *m = Asset{} }
func (m *Asset) String() string            { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()               {}
func (*Asset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Asset) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Asset) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func init() {
	proto.RegisterType((*Asset)(nil), "lmsr.Asset")
}

func init() { proto.RegisterFile("lmsr/asset.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0xc9, 0x2d, 0x2e,
	0xd2, 0x4f, 0x2c, 0x2e, 0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x89,
	0x28, 0xe9, 0x73, 0xb1, 0x3a, 0x82, 0x04, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0xc4, 0xb8, 0xd8, 0xca, 0xf2, 0x73, 0x4a, 0x73,
	0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x18, 0x83, 0xa0, 0xbc, 0x24, 0x36, 0xb0, 0x6e, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xf8, 0x6f, 0xc3, 0x51, 0x00, 0x00, 0x00,
}
