// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lmsr/data.proto

/*
Package lmsr is a generated protocol buffer package.

It is generated from these files:
	lmsr/data.proto

It has these top-level messages:
	Outcome
	Event
	Market
	Markets
	Asset
	Assets
*/
package lmsr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Event
type Outcome struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *Outcome) Reset()                    { *m = Outcome{} }
func (m *Outcome) String() string            { return proto.CompactTextString(m) }
func (*Outcome) ProtoMessage()               {}
func (*Outcome) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Outcome) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Outcome) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Event struct {
	Id       string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	User     string     `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Title    string     `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Outcomes []*Outcome `protobuf:"bytes,4,rep,name=outcomes" json:"outcomes,omitempty"`
	Result   string     `protobuf:"bytes,5,opt,name=result" json:"result,omitempty"`
	Approved bool       `protobuf:"varint,6,opt,name=approved" json:"approved,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetOutcomes() []*Outcome {
	if m != nil {
		return m.Outcomes
	}
	return nil
}

func (m *Event) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *Event) GetApproved() bool {
	if m != nil {
		return m.Approved
	}
	return false
}

// Market
type Market struct {
	Id        string             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	User      string             `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Event     string             `protobuf:"bytes,3,opt,name=event" json:"event,omitempty"`
	Liquidity float64            `protobuf:"fixed64,4,opt,name=liquidity" json:"liquidity,omitempty"`
	Fund      float64            `protobuf:"fixed64,5,opt,name=fund" json:"fund,omitempty"`
	Cost      float64            `protobuf:"fixed64,6,opt,name=cost" json:"cost,omitempty"`
	Shares    map[string]float64 `protobuf:"bytes,7,rep,name=shares" json:"shares,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Prices    map[string]float64 `protobuf:"bytes,8,rep,name=prices" json:"prices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Settled   bool               `protobuf:"varint,9,opt,name=settled" json:"settled,omitempty"`
}

func (m *Market) Reset()                    { *m = Market{} }
func (m *Market) String() string            { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()               {}
func (*Market) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Market) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Market) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Market) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Market) GetLiquidity() float64 {
	if m != nil {
		return m.Liquidity
	}
	return 0
}

func (m *Market) GetFund() float64 {
	if m != nil {
		return m.Fund
	}
	return 0
}

func (m *Market) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Market) GetShares() map[string]float64 {
	if m != nil {
		return m.Shares
	}
	return nil
}

func (m *Market) GetPrices() map[string]float64 {
	if m != nil {
		return m.Prices
	}
	return nil
}

func (m *Market) GetSettled() bool {
	if m != nil {
		return m.Settled
	}
	return false
}

type Markets struct {
	List []*Market `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *Markets) Reset()                    { *m = Markets{} }
func (m *Markets) String() string            { return proto.CompactTextString(m) }
func (*Markets) ProtoMessage()               {}
func (*Markets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Markets) GetList() []*Market {
	if m != nil {
		return m.List
	}
	return nil
}

type Asset struct {
	Id     string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Volume float64 `protobuf:"fixed64,2,opt,name=volume" json:"volume,omitempty"`
}

func (m *Asset) Reset()                    { *m = Asset{} }
func (m *Asset) String() string            { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()               {}
func (*Asset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Asset) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Asset) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

type Assets struct {
	List []*Asset `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *Assets) Reset()                    { *m = Assets{} }
func (m *Assets) String() string            { return proto.CompactTextString(m) }
func (*Assets) ProtoMessage()               {}
func (*Assets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Assets) GetList() []*Asset {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Outcome)(nil), "lmsr.Outcome")
	proto.RegisterType((*Event)(nil), "lmsr.Event")
	proto.RegisterType((*Market)(nil), "lmsr.Market")
	proto.RegisterType((*Markets)(nil), "lmsr.Markets")
	proto.RegisterType((*Asset)(nil), "lmsr.Asset")
	proto.RegisterType((*Assets)(nil), "lmsr.Assets")
}

func init() { proto.RegisterFile("lmsr/data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcb, 0x6e, 0xdb, 0x30,
	0x10, 0x04, 0x65, 0xbd, 0xbc, 0xee, 0x0b, 0x44, 0x61, 0x10, 0x46, 0x81, 0x0a, 0x3a, 0xc9, 0x28,
	0x20, 0x17, 0xed, 0xa5, 0xed, 0xad, 0x07, 0x1f, 0x8b, 0x06, 0xcc, 0x17, 0x28, 0x16, 0x83, 0x10,
	0xa6, 0x2d, 0x85, 0xa4, 0x04, 0xf8, 0x6f, 0xf2, 0xa1, 0x39, 0x04, 0x5c, 0xca, 0xb6, 0x82, 0xf8,
	0x90, 0xdc, 0x76, 0x76, 0x77, 0x66, 0x67, 0x44, 0xc1, 0x47, 0xb5, 0x33, 0x7a, 0x55, 0x57, 0xb6,
	0x2a, 0x5b, 0xdd, 0xd8, 0x86, 0x86, 0xae, 0x91, 0xaf, 0x20, 0xf9, 0xdf, 0xd9, 0x4d, 0xb3, 0x13,
	0xf4, 0x03, 0x04, 0xb2, 0x66, 0x24, 0x23, 0xc5, 0x94, 0x07, 0xb2, 0xa6, 0x9f, 0x21, 0xb2, 0xd2,
	0x2a, 0xc1, 0x02, 0x6c, 0x79, 0x90, 0x3f, 0x10, 0x88, 0xd6, 0xbd, 0xd8, 0xdb, 0x17, 0xfb, 0x14,
	0xc2, 0xce, 0x08, 0x3d, 0xac, 0x63, 0x7d, 0xd6, 0x98, 0x8c, 0x34, 0xe8, 0x12, 0xd2, 0xc6, 0x1f,
	0x35, 0x2c, 0xcc, 0x26, 0xc5, 0xec, 0xc7, 0xfb, 0xd2, 0xb9, 0x29, 0x07, 0x2b, 0xfc, 0x34, 0xa6,
	0x73, 0x88, 0xb5, 0x30, 0x9d, 0xb2, 0x2c, 0x42, 0x85, 0x01, 0xd1, 0x05, 0xa4, 0x55, 0xdb, 0xea,
	0xa6, 0x17, 0x35, 0x8b, 0x33, 0x52, 0xa4, 0xfc, 0x84, 0xf3, 0xc7, 0x00, 0xe2, 0x7f, 0x95, 0xde,
	0x8a, 0x57, 0x7b, 0x14, 0x2e, 0xd0, 0xd1, 0x23, 0x02, 0xfa, 0x05, 0xa6, 0x4a, 0xde, 0x77, 0xb2,
	0x96, 0xf6, 0xc0, 0xc2, 0x8c, 0x14, 0x84, 0x9f, 0x1b, 0x4e, 0xe7, 0xb6, 0xdb, 0xd7, 0x68, 0x8a,
	0x70, 0xac, 0x5d, 0x6f, 0xd3, 0x18, 0x8b, 0x76, 0x08, 0xc7, 0x9a, 0x7e, 0x87, 0xd8, 0xdc, 0x55,
	0x5a, 0x18, 0x96, 0x60, 0x4e, 0xe6, 0x73, 0x7a, 0x77, 0xe5, 0x35, 0x8e, 0xd6, 0x7b, 0xab, 0x0f,
	0x7c, 0xd8, 0x73, 0x8c, 0x56, 0xcb, 0x8d, 0x30, 0x2c, 0xbd, 0xc0, 0xb8, 0xc2, 0xd1, 0xc0, 0xf0,
	0x7b, 0x94, 0x41, 0x62, 0x84, 0xb5, 0x4a, 0xd4, 0x6c, 0x8a, 0x5f, 0xe2, 0x08, 0x17, 0xbf, 0x61,
	0x36, 0x3a, 0x41, 0x3f, 0xc1, 0x64, 0x2b, 0x0e, 0xc3, 0xd7, 0x70, 0xa5, 0x8b, 0xde, 0x57, 0xaa,
	0xf3, 0x4f, 0x4c, 0xb8, 0x07, 0x7f, 0x82, 0x5f, 0xc4, 0x51, 0x47, 0xb7, 0xde, 0x42, 0xcd, 0xbf,
	0x41, 0xe2, 0xdd, 0x1a, 0x9a, 0x41, 0xa8, 0xa4, 0xb1, 0x8c, 0x60, 0x94, 0x77, 0xe3, 0x28, 0x1c,
	0x27, 0xf9, 0x0a, 0xa2, 0xbf, 0xc6, 0x5c, 0x78, 0xa9, 0x39, 0xc4, 0x7d, 0xa3, 0xba, 0xdd, 0xf1,
	0xc0, 0x80, 0xf2, 0x25, 0xc4, 0x48, 0x30, 0xf4, 0xeb, 0x33, 0xf1, 0x99, 0x17, 0xc7, 0x99, 0xd7,
	0xbe, 0x89, 0xf1, 0x47, 0xff, 0xf9, 0x14, 0x00, 0x00, 0xff, 0xff, 0x89, 0xc2, 0xae, 0xc7, 0xfb,
	0x02, 0x00, 0x00,
}
